# Generated by Django 5.2.1 on 2025-12-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alertrule',
            new_name='dashboard_a_metric__60ebe4_idx',
            old_name='dashboard_alertrule_metric_active_idx',
        ),
        migrations.RenameIndex(
            model_name='alertrule',
            new_name='dashboard_a_severit_fd0f71_idx',
            old_name='dashboard_alertrule_severity_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='dashboard_a_timesta_3a0d49_idx',
            old_name='dashboard_auditlog_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='dashboard_a_action__8126f5_idx',
            old_name='dashboard_auditlog_action_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='dashboard_a_app_lab_26b48b_idx',
            old_name='dashboard_auditlog_model_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='dashboard_a_object__25faa4_idx',
            old_name='dashboard_auditlog_object_idx',
        ),
        migrations.RenameIndex(
            model_name='incident',
            new_name='dashboard_i_status_a981c3_idx',
            old_name='dashboard_incident_status_severity_idx',
        ),
        migrations.RenameIndex(
            model_name='incident',
            new_name='dashboard_i_created_f7dd8f_idx',
            old_name='dashboard_incident_created_at_idx',
        ),
    ]
